# Generated by Django 3.1.7 on 2022-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20220802_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='説明'),
        ),
        migrations.AlterModelTable(
            name='memo',
            table='db_memo',
        ),
    ]
